.DEFAULT_GOAL := help
SHELL := /bin/bash
UV    := uv

# ---------------------------------------------------------------------------
# Help — `make` with no args prints this list.
# ---------------------------------------------------------------------------
.PHONY: help
help:  ## Show this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage: make \033[36m<target>\033[0m\n"} \
		/^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)

# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------
.PHONY: install
install:  ## Install all deps including dev extras.
	$(UV) sync --all-extras

.PHONY: hooks
hooks:  ## Install git hooks via pre-commit.
	$(UV) run pre-commit install --install-hooks
	$(UV) run pre-commit install --hook-type commit-msg
	$(UV) run pre-commit install --hook-type pre-push

.PHONY: env
env:  ## Copy .env.example → .env (only if missing).
	@test -f .env || cp .env.example .env

# ---------------------------------------------------------------------------
# Lint / format / type-check
# ---------------------------------------------------------------------------
.PHONY: fmt
fmt:  ## Format code with ruff.
	$(UV) run ruff format src tests
	$(UV) run ruff check --fix src tests

.PHONY: lint
lint:  ## Lint with ruff.
	$(UV) run ruff check src tests
	$(UV) run ruff format --check src tests

.PHONY: typecheck
typecheck:  ## Static type-check.
	$(UV) run mypy src

.PHONY: check
check: lint typecheck  ## Lint + typecheck.

# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------
.PHONY: test
test:  ## Run all tests with coverage.
	$(UV) run pytest

.PHONY: test-unit
test-unit:  ## Unit tests only.
	$(UV) run pytest -m unit

.PHONY: test-int
test-int:  ## Integration tests only.
	$(UV) run pytest -m integration

.PHONY: smoke
smoke:  ## Smoke-test a running instance. Usage: make smoke URL=http://localhost:8000
	./scripts/smoke.sh $(URL)

# ---------------------------------------------------------------------------
# Run / serve
# ---------------------------------------------------------------------------
.PHONY: run
run:  ## Run the app with auto-reload.
	$(UV) run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir src

.PHONY: serve
serve:  ## Run gunicorn locally (prod-style).
	$(UV) run gunicorn app.main:app \
		--bind 0.0.0.0:8000 \
		--workers 4 \
		--worker-class uvicorn.workers.UvicornWorker

# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------
.PHONY: db-up
db-up:  ## Start Postgres + Redis in docker.
	docker compose up -d postgres redis

.PHONY: db-down
db-down:  ## Stop Postgres + Redis.
	docker compose stop postgres redis

.PHONY: db-shell
db-shell:  ## Open a psql shell in the running Postgres container.
	docker compose exec postgres psql -U postgres -d app

.PHONY: migrate
migrate:  ## Apply pending migrations.
	$(UV) run alembic upgrade head

.PHONY: migration
migration:  ## Create a new autogenerated migration. Usage: make migration m="add users table"
	$(UV) run alembic revision --autogenerate -m "$(m)"

.PHONY: downgrade
downgrade:  ## Roll back one migration.
	$(UV) run alembic downgrade -1

# ---------------------------------------------------------------------------
# Docker
# ---------------------------------------------------------------------------
.PHONY: docker-build
docker-build:  ## Build the API image.
	docker compose build api

.PHONY: docker-up
docker-up:  ## Start the full stack.
	docker compose up -d

.PHONY: docker-down
docker-down:  ## Stop and remove all containers.
	docker compose down

.PHONY: docker-logs
docker-logs:  ## Tail API logs.
	docker compose logs -f api

# ---------------------------------------------------------------------------
# Maintenance
# ---------------------------------------------------------------------------
.PHONY: clean
clean:  ## Remove build artefacts and caches.
	find . -type d -name __pycache__ -exec rm -rf {} +
	rm -rf .pytest_cache .mypy_cache .ruff_cache .coverage coverage.xml htmlcov dist build *.egg-info

.PHONY: lock
lock:  ## Re-resolve the lockfile.
	$(UV) lock
